---
- name: "Build hosts file on remote server from local file"
  vars:
     file_contents: "{{lookup('file', '../base_hosts_file.txt').splitlines()}}"
  lineinfile:
     path: /etc/hosts
     line: "{{ item }}"
     create: yes
     state: present
  with_items: "{{ file_contents }}"
- name: "Create flag file for hosts build task"
  lineinfile:
     path: /etc/hosts_built_ansible
     line: "Ansible was here"
     create: yes
     state: present
